// Project-overview fixtures, generated by Rust.
//
// `fixtures/project-overview.generated.json` is written by
// `crates/tracking/tests/status_contract.rs`, which serializes the REAL
// `tracking_project::ProjectOverview` for every user-visible tracking state and
// fails if the committed file differs. So the objects below are the bytes
// `project_tracking_overview` actually returns.
//
// This exists because the audited defect survived a full frontend suite: every
// test passed `status: null`, and the one declared shape was another command's
// DTO, so the project page read `status.health.currently_working` — a key the
// payload cannot contain — and rendered "needs attention" for a healthy project
// forever (AUD-05). A hand-written fixture cannot catch that. A generated one
// cannot express it.

import type { ProjectOverview, TrackingStateTag } from "../types";
import generated from "./fixtures/project-overview.generated.json";

/**
 * The fixture keys, which are scenario names rather than state tokens: two
 * fixtures deliberately project to the same state (`gateway_unavailable`), and
 * three describe structural situations rather than health.
 */
export type FixtureName = Exclude<keyof typeof generated, "_generated_by">;

/**
 * TypeScript widens every string in an imported JSON file to `string`, so no
 * assignability check is possible here and the cast would be a lie if left
 * unchecked. It is checked instead — at runtime, in
 * `ProjectTrackingStatus.test.tsx`, against the declared unions and against the
 * required-field list. That is the assertion; this is the accessor.
 */
export function fixture(name: FixtureName): ProjectOverview {
  const raw = generated[name] as unknown;
  // Cloned so a test that mutates a fixture cannot leak into the next one.
  return JSON.parse(JSON.stringify(raw)) as ProjectOverview;
}

/** Every fixture, for tests that assert across all of them. */
export function everyFixture(): [FixtureName, ProjectOverview][] {
  return (Object.keys(generated) as (keyof typeof generated)[])
    .filter((k): k is FixtureName => k !== "_generated_by")
    .map((k) => [k, fixture(k)]);
}

/**
 * Every state token the TypeScript union declares.
 *
 * Typed as `TrackingStateTag[]`, so removing a member from the union in
 * `types.ts` without removing it here is a compile error, and the runtime
 * comparison against what Rust emits closes the other direction.
 */
export const DECLARED_STATE_TAGS: readonly TrackingStateTag[] = [
  "not_linked",
  "tracking_off",
  "folder_missing",
  "awaiting_setup",
  "tracking_on",
  "partially_tracked",
  "waiting_for_first_request",
  "restart_required",
  "gateway_unavailable",
  "route_unavailable",
  "project_link_unavailable",
  "idle",
  "configuration_changed",
  "attribution_paused",
  "setup_incomplete",
  "needs_attention",
  "unsupported",
];
