//! Local alerts with a create → acknowledge → resolve lifecycle.
//!
//! Alerts are generated by the [`crate::monitor`] from evidence the vault
//! already holds (expiration, staleness, reuse, exposure, documentation
//! changes). Each alert carries its rule, severity, evidence, confidence, and
//! recommended action. A `dedup_key` keeps a single *open* alert per
//! underlying condition, so re-running checks refreshes rather than
//! duplicates. Alert rows never contain secret values.

use crate::clock;
use crate::error::{CoreError, Result};
use crate::providers::Confidence;
use rusqlite::{params, Connection, OptionalExtension, Row};
use serde::Serialize;
use uuid::Uuid;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertKind {
    ExpiringSoon,
    Expired,
    Stale,
    Unused,
    ReusedAcrossProjects,
    ProductionInDevelopment,
    PossibleExposure,
    ProviderSyncFailed,
    DocumentationChanged,
    OverBudget,
    CostSpike,
    UsageAfterDisabled,
    CredentialActivated,
}

impl AlertKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            AlertKind::ExpiringSoon => "expiring_soon",
            AlertKind::Expired => "expired",
            AlertKind::Stale => "stale",
            AlertKind::Unused => "unused",
            AlertKind::ReusedAcrossProjects => "reused_across_projects",
            AlertKind::ProductionInDevelopment => "production_in_development",
            AlertKind::PossibleExposure => "possible_exposure",
            AlertKind::ProviderSyncFailed => "provider_sync_failed",
            AlertKind::DocumentationChanged => "documentation_changed",
            AlertKind::OverBudget => "over_budget",
            AlertKind::CostSpike => "cost_spike",
            AlertKind::UsageAfterDisabled => "usage_after_disabled",
            AlertKind::CredentialActivated => "credential_activated",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Low,
    Medium,
    High,
    Critical,
}

impl Severity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Info => "info",
            Severity::Low => "low",
            Severity::Medium => "medium",
            Severity::High => "high",
            Severity::Critical => "critical",
        }
    }
}

/// A new alert to be recorded (upserted by `dedup_key`).
#[derive(Debug, Clone)]
pub struct NewAlert {
    pub kind: AlertKind,
    pub severity: Severity,
    pub dedup_key: String,
    pub title: String,
    pub detail: String,
    pub evidence: String,
    pub confidence: Confidence,
    pub recommended_action: String,
    pub project_id: Option<String>,
    pub credential_id: Option<String>,
    pub observed_at: String,
}

/// A stored alert.
#[derive(Debug, Clone, Serialize)]
pub struct Alert {
    pub id: String,
    pub kind: String,
    pub severity: String,
    pub title: String,
    pub detail: String,
    pub evidence: String,
    pub confidence: String,
    pub recommended_action: String,
    pub project_id: Option<String>,
    pub credential_id: Option<String>,
    pub created_at: String,
    pub observed_at: String,
    pub acknowledged_at: Option<String>,
    pub resolved_at: Option<String>,
}

const COLUMNS: &str = "id, kind, severity, title, detail, evidence, confidence, \
     recommended_action, project_id, credential_id, created_at, observed_at, \
     acknowledged_at, resolved_at";

fn row_to_alert(row: &Row<'_>) -> rusqlite::Result<Alert> {
    Ok(Alert {
        id: row.get(0)?,
        kind: row.get(1)?,
        severity: row.get(2)?,
        title: row.get(3)?,
        detail: row.get(4)?,
        evidence: row.get(5)?,
        confidence: row.get(6)?,
        recommended_action: row.get(7)?,
        project_id: row.get(8)?,
        credential_id: row.get(9)?,
        created_at: row.get(10)?,
        observed_at: row.get(11)?,
        acknowledged_at: row.get(12)?,
        resolved_at: row.get(13)?,
    })
}

/// Insert or refresh an open alert keyed by `dedup_key`. If an open alert
/// with the same key exists it is updated in place (observed time, detail,
/// evidence, severity); otherwise a new one is created. Returns whether a new
/// alert was created.
pub fn upsert(conn: &Connection, alert: &NewAlert) -> Result<bool> {
    let existing: Option<String> = conn
        .query_row(
            "SELECT id FROM alerts WHERE dedup_key = ?1 AND resolved_at IS NULL",
            [&alert.dedup_key],
            |r| r.get(0),
        )
        .optional()?;
    if let Some(id) = existing {
        conn.execute(
            "UPDATE alerts SET severity = ?1, title = ?2, detail = ?3, evidence = ?4,
             confidence = ?5, recommended_action = ?6, observed_at = ?7 WHERE id = ?8",
            params![
                alert.severity.as_str(),
                alert.title,
                alert.detail,
                alert.evidence,
                alert.confidence.label(),
                alert.recommended_action,
                alert.observed_at,
                id,
            ],
        )?;
        Ok(false)
    } else {
        let id = Uuid::new_v4().to_string();
        // ON CONFLICT against the partial unique index makes this atomic: if a
        // concurrent monitor run (desktop + CLI) inserted the same open alert
        // between our SELECT and this INSERT, we update in place instead of
        // aborting on a unique-constraint violation.
        let inserted = conn.execute(
            "INSERT INTO alerts (id, kind, severity, dedup_key, title, detail, evidence,
             confidence, recommended_action, project_id, credential_id, created_at, observed_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
             ON CONFLICT(dedup_key) WHERE resolved_at IS NULL DO UPDATE SET
             severity = excluded.severity, title = excluded.title, detail = excluded.detail,
             evidence = excluded.evidence, confidence = excluded.confidence,
             recommended_action = excluded.recommended_action, observed_at = excluded.observed_at",
            params![
                id,
                alert.kind.as_str(),
                alert.severity.as_str(),
                alert.dedup_key,
                alert.title,
                alert.detail,
                alert.evidence,
                alert.confidence.label(),
                alert.recommended_action,
                alert.project_id,
                alert.credential_id,
                clock::now_rfc3339(),
                alert.observed_at,
            ],
        )?;
        Ok(inserted > 0)
    }
}

/// Resolve any open alerts whose dedup_key is not in `active_keys` and whose
/// kind is in `kinds` — i.e. conditions that no longer hold after a check.
/// Returns the number auto-resolved.
pub fn auto_resolve_stale(
    conn: &Connection,
    kinds: &[AlertKind],
    active_keys: &[String],
) -> Result<usize> {
    if kinds.is_empty() {
        return Ok(0);
    }
    let mut open_ids: Vec<(String, String)> = Vec::new();
    {
        let placeholders = kinds.iter().map(|_| "?").collect::<Vec<_>>().join(",");
        let sql = format!(
            "SELECT id, dedup_key FROM alerts WHERE resolved_at IS NULL AND kind IN ({placeholders})"
        );
        let mut stmt = conn.prepare(&sql)?;
        let kind_strs: Vec<&'static str> = kinds.iter().map(|k| k.as_str()).collect();
        let params: Vec<&dyn rusqlite::ToSql> = kind_strs
            .iter()
            .map(|s| s as &dyn rusqlite::ToSql)
            .collect();
        let rows = stmt.query_map(params.as_slice(), |r| {
            Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?))
        })?;
        for row in rows {
            open_ids.push(row?);
        }
    }
    let now = clock::now_rfc3339();
    let mut resolved = 0;
    for (id, key) in open_ids {
        if !active_keys.contains(&key) {
            conn.execute(
                "UPDATE alerts SET resolved_at = ?1 WHERE id = ?2",
                params![now, id],
            )?;
            resolved += 1;
        }
    }
    Ok(resolved)
}

/// List alerts. When `include_resolved` is false, only open alerts are shown.
pub fn list(conn: &Connection, include_resolved: bool) -> Result<Vec<Alert>> {
    let sql = if include_resolved {
        format!("SELECT {COLUMNS} FROM alerts ORDER BY created_at DESC")
    } else {
        format!("SELECT {COLUMNS} FROM alerts WHERE resolved_at IS NULL ORDER BY created_at DESC")
    };
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map([], row_to_alert)?;
    let mut out = Vec::new();
    for r in rows {
        out.push(r?);
    }
    Ok(out)
}

fn resolve_id(conn: &Connection, id_or_prefix: &str) -> Result<String> {
    if let Some(id) = conn
        .query_row("SELECT id FROM alerts WHERE id = ?1", [id_or_prefix], |r| {
            r.get::<_, String>(0)
        })
        .optional()?
    {
        return Ok(id);
    }
    let mut stmt = conn.prepare("SELECT id FROM alerts WHERE id LIKE ?1")?;
    let like = format!("{id_or_prefix}%");
    let ids: Vec<String> = stmt
        .query_map([like], |r| r.get::<_, String>(0))?
        .collect::<rusqlite::Result<_>>()?;
    match ids.len() {
        0 => Err(CoreError::NotFound {
            kind: "alert",
            ident: id_or_prefix.to_owned(),
        }),
        1 => Ok(ids.into_iter().next().expect("len checked")),
        _ => Err(CoreError::Ambiguous {
            kind: "alert",
            ident: id_or_prefix.to_owned(),
        }),
    }
}

pub fn acknowledge(conn: &Connection, id_or_prefix: &str) -> Result<Alert> {
    let id = resolve_id(conn, id_or_prefix)?;
    conn.execute(
        "UPDATE alerts SET acknowledged_at = COALESCE(acknowledged_at, ?1) WHERE id = ?2",
        params![clock::now_rfc3339(), id],
    )?;
    get(conn, &id)
}

pub fn resolve(conn: &Connection, id_or_prefix: &str) -> Result<Alert> {
    let id = resolve_id(conn, id_or_prefix)?;
    conn.execute(
        "UPDATE alerts SET resolved_at = COALESCE(resolved_at, ?1) WHERE id = ?2",
        params![clock::now_rfc3339(), id],
    )?;
    get(conn, &id)
}

pub fn get(conn: &Connection, id: &str) -> Result<Alert> {
    conn.query_row(
        &format!("SELECT {COLUMNS} FROM alerts WHERE id = ?1"),
        [id],
        row_to_alert,
    )
    .optional()?
    .ok_or_else(|| CoreError::NotFound {
        kind: "alert",
        ident: id.to_owned(),
    })
}

pub fn open_count(conn: &Connection) -> Result<i64> {
    Ok(conn.query_row(
        "SELECT count(*) FROM alerts WHERE resolved_at IS NULL",
        [],
        |r| r.get(0),
    )?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;

    fn mem() -> Connection {
        let mut conn = Connection::open_in_memory().unwrap();
        db::migrate(&mut conn).unwrap();
        conn
    }

    fn sample(dedup: &str, kind: AlertKind) -> NewAlert {
        NewAlert {
            kind,
            severity: Severity::Medium,
            dedup_key: dedup.to_string(),
            title: "t".into(),
            detail: "d".into(),
            evidence: "e".into(),
            confidence: Confidence::High,
            recommended_action: "do x".into(),
            project_id: None,
            credential_id: None,
            observed_at: clock::now_rfc3339(),
        }
    }

    #[test]
    fn upsert_dedups_open_alerts() {
        let conn = mem();
        assert!(upsert(&conn, &sample("k1", AlertKind::Expired)).unwrap());
        assert!(!upsert(&conn, &sample("k1", AlertKind::Expired)).unwrap());
        assert_eq!(open_count(&conn).unwrap(), 1);
        assert!(upsert(&conn, &sample("k2", AlertKind::Stale)).unwrap());
        assert_eq!(open_count(&conn).unwrap(), 2);
    }

    #[test]
    fn lifecycle_acknowledge_then_resolve() {
        let conn = mem();
        upsert(&conn, &sample("k1", AlertKind::Expired)).unwrap();
        let id = list(&conn, false).unwrap()[0].id.clone();

        let acked = acknowledge(&conn, &id[..8]).unwrap();
        assert!(acked.acknowledged_at.is_some());
        assert!(acked.resolved_at.is_none());

        let resolved = resolve(&conn, &id).unwrap();
        assert!(resolved.resolved_at.is_some());
        assert_eq!(open_count(&conn).unwrap(), 0);

        // A new alert with the same dedup key can be opened again after resolve.
        assert!(upsert(&conn, &sample("k1", AlertKind::Expired)).unwrap());
        assert_eq!(open_count(&conn).unwrap(), 1);
    }

    #[test]
    fn auto_resolve_clears_conditions_that_no_longer_hold() {
        let conn = mem();
        upsert(&conn, &sample("expired:cred1", AlertKind::Expired)).unwrap();
        upsert(&conn, &sample("expired:cred2", AlertKind::Expired)).unwrap();
        // Only cred1 is still expiring; cred2's condition cleared.
        let resolved =
            auto_resolve_stale(&conn, &[AlertKind::Expired], &["expired:cred1".to_string()])
                .unwrap();
        assert_eq!(resolved, 1);
        assert_eq!(open_count(&conn).unwrap(), 1);
    }

    #[test]
    fn alerts_never_serialize_secret_material() {
        let conn = mem();
        upsert(&conn, &sample("k1", AlertKind::PossibleExposure)).unwrap();
        let json = serde_json::to_string(&list(&conn, true).unwrap()).unwrap();
        assert!(json.contains("possible_exposure"));
    }
}
